config/routes.rb
Rails.application.routes.draw do
  #root
  root "sessions#home"

  #signup
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login
  get '/login' => 'sessions#login'
  post '/login' => 'sessions#create'

  #logged_in
  get '/user' => 'users#show'

  #logout
  delete '/logout' => 'sessions#destroy'

  #search planets
  get '/search' => 'planets#search'
  
  resources :moons
  resources :comments
  resources :users do
    resources :planets, only: [:new, :create, :index, :show]
    resources :moons, only: [:new, :create, :index, :show]
  end

  resources :planets do
    resources :comments
  end


  get '/auth/google_oauth2/callback', to: 'sessions#google_login'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :planet

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_comment, only: [:show, :edit, :update]
    before_action :redirect_if_not_comment_author, only: [:edit, :update]

    def index
        if params[:planet_id] && @planet = Planet.find_by_id(params[:planet_id])
            @comments = @planet.comments
        else
            flash[:message] = "That planet doesn't exist" if params[:planet_id]
            @comments = Comment.new
        end
    end

    def new
        if params[:planet_id] && @planet = Planet.find_by_id(params[:planet_id])
            @comment = @planet.comments.build
        else
            @error = "That planet doesn't exist" if params[:planet_id]
            @comment = Comment.new
        end
    end

    def create
        @comment = current_user.comments.build(comment_params)
        if @comment.save
            redirect_to planets_path
        else
            render :new
        end 
    end

    def show
        
    end

    def edit
        
    end

    def update
        if @comment.update(comment_params)
            redirect_to comment_path(@comment)
        else
            render :edit
        end
    end

    def destroy
        @comment = Comment.find_by_id(params[:id])
        @comment.destroy
        redirect_to planets_path
    end

    private

    def comment_params
        params.require(:comment).permit(:content, :planet_id)
    end

    def set_comment
        @comment = Comment.find_by_id(params[:id])
        if !@comment
            flash[:message] = "Comment was not found."
            redirect_to comments_path
        end
    end

    def redirect_if_not_comment_author
        redirect_to comments_path if @comment.user != current_user
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= render partial: "layouts/errors", locals: {object: @comment} %>

<%= form_with(model: @comment, local: true) do |form| %>
    
    <div class="fields">
        <% if !@comment.planet %>
            <%= form.label :planet %>
            <br>
            <%= form.collection_select :planet_id, Planet.all, :id, :name %>
            <br>
            <br>
        <% else %>
            <%= form.hidden_field :planet_id %>
        <% end %>
    </div>

    <div class="fields">
        <%= form.label :content %>
        <br>
        <%= form.text_area :content %>
        <br>
        <br>
    </div>

    <div class="actions">
        <%= form.submit 'Submit' %>
    </div>
<% end %>
<br>

app/views/comments/edit.html.erb
<h1 align="center">Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', planets_path %>

app/views/comments/index.html.erb
<% if @planet %>
    <h1 align="center">Comments for <%= @planet.name %></h1>
<% else %>
    <h1 align="center">All Comments</h1>
<% end %>

<% if @planet %>
    <% @comments.in_groups_of(3) do |group| %>
        <div class="row">
        <% group.compact.each do |comment| %>
            <strong><%= comment.user.username%></strong> says "<%= comment.content%>" about this planet: <strong><%= link_to comment.planet.name, planet_path(comment.planet_id) %></strong>
            <br>
            <%= link_to 'Edit', edit_planet_comment_path(@planet,comment) %> |
            <%= link_to 'Back', planet_comments_path %>
            <br><br>
        <% end %>
        </div>
    <% end %>
<% end %>

app/views/comments/new.html.erb
<h1 align="center">New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', planets_path %>

app/views/comments/show.html.erb
<h3 align="center"><%= @comment.content %> - <%= @comment.user.username %></h3>
<br>
<p align="center">
    <% if @comment.user == current_user %>
        <%= link_to "Edit Comment", edit_comment_path(@comment) %> |
        <%= link_to "Delete Comment", comment_path(@comment) %>
    <% end %>
</p>
<h4 align="center">Read the post here: <%= link_to @comment.planet.name, planet_path(@comment.planet_id) %></h4>