config/routes.rb
Rails.application.routes.draw do
  #root
  root "sessions#home"

  #signup
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login
  get '/login' => 'sessions#login'
  post '/login' => 'sessions#create'

  #logged_in
  get '/user' => 'users#show'

  #logout
  delete '/logout' => 'sessions#destroy'

  #search planets
  get '/search' => 'planets#search'
  
  resources :moons
  resources :comments
  resources :users do
    resources :planets, only: [:new, :create, :index, :show]
    resources :moons, only: [:new, :create, :index, :show]
  end

  resources :planets do
    resources :comments
  end


  get '/auth/google_oauth2/callback', to: 'sessions#google_login'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :planets
    has_many :moons
    has_many :comments
    has_many :commented_planets, through: :comments, source: :planet

    validates :email, presence: true, uniqueness: true
    validates :username, presence: true, uniqueness: true
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else    
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        return '/' if !@user
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1 align="center">Sign Up!</h1>

<div align="center">
    <%= form_with model: @user, local: true do |f| %>
        
        <% if @user.errors.any? %>
            <p>There were errors:</p>
            <p><%= @user.errors.full_messages.join(" | ") %></p>
        <% end %>

        <%= f.label :username %>
        <%= f.text_field :username %>
        <br>
        <br>

        <%= f.label :email %>
        <%= f.email_field :email %>
        <br>
        <br>

        <%= f.label :password %>
        <%= f.password_field :password %>
        <br>
        <br>

        <%= f.submit 'Sign Up!' %>

    <% end %>
</div>

app/views/users/show.html.erb
<h1 align="center"><b>Hello, <%= current_user.username %>!</b></h1>
<br>
<ul>
    <h4 align="center"><%= link_to 'All Planets', planets_path %></h4>
    <br>
    <h4 align="center"><%= link_to 'Add a New Planet', new_user_planet_path(current_user) %></h4>
    <br>
    <h4 align="center"><%= link_to 'All Moons', moons_path %></h4>
    <br>
    <h4 align="center"><%= link_to 'Add a New Moon', new_user_moon_path(current_user) %></h4>
    <br>
</ul>