config/routes.rb
Rails.application.routes.draw do
  #root
  root "sessions#home"

  #signup
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login
  get '/login' => 'sessions#login'
  post '/login' => 'sessions#create'

  #logged_in
  get '/user' => 'users#show'

  #logout
  delete '/logout' => 'sessions#destroy'

  #search planets
  get '/search' => 'planets#search'
  
  resources :moons
  resources :comments
  resources :users do
    resources :planets, only: [:new, :create, :index, :show]
    resources :moons, only: [:new, :create, :index, :show]
  end

  resources :planets do
    resources :comments
  end


  get '/auth/google_oauth2/callback', to: 'sessions#google_login'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/planet.rb
class Planet < ApplicationRecord
    belongs_to :user
    has_many :comments, :dependent => :destroy
    has_many :users, through: :comments
    validates :name, :description, presence: true

    scope :alphabetize_planets, -> { order(name: :asc) }

    #scope :search, -> { where("lower(name) LIKE '#{search.downcase}%'")}

    mount_uploader :image, ImageUploader

    def self.search(search)
        where("lower(name) LIKE '#{search.downcase}%'")
    end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
    before_action :redirect_if_not_logged_in

    def index
        if params[:search]
            @planets = current_user.planets.search(params[:search]).order(name: :asc)
        else
            @planets = current_user.planets.alphabetize_planets
        end
    end

    def new
        @planet = Planet.new
    end

    def create
        @planet = current_user.planets.build(planet_params)
        if @planet.save
            redirect_to planets_path
        else
            render :new
        end
    end 

    def show
        @planet = current_user.planets.find_by_id(params[:id])
    end

    def edit
        @planet = current_user.planets.find_by_id(params[:id])
    end

    def update
        planet = Planet.find_by(id: params[:id])
        planet.update(planet_params)
        redirect_to planet_path(planet)
    end

    def destroy
        @planet = Planet.find_by(id: params[:id])
        @planet.destroy
        redirect_to planets_path
    end

    private

    def planet_params
        params.require(:planet).permit(:name, :type_of_planet, :description, :length_of_year, :distance_from_sun, :moons, :image, :search)
    end
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/planets/_form.html.erb
<%= render partial: "layouts/errors", locals: {object: @planet} %>

<%= form_with(model: @planet, local: true) do |form| %>
    
    <div class="fields">
        <%= form.label :name %>
        <br>
        <%= form.text_field :name %>
        <br>
        <br>
    </div>

    <div class="fields">
        <%= form.label :type_of_planet %>
        <br>
        <%= form.text_field :type_of_planet %>
        <br>
        <br>
    </div>

    <div class="fields">
        <%= form.label :description %>
        <br>
        <%= form.text_area :description %>
        <br>
        <br>
    </div>

    <div class="fields">
        <%= form.label :length_of_year %>
        <br>
        <%= form.text_field :length_of_year %> (In Days.)
        <br>
        <br>
    </div>

    <div class="fields">
        <%= form.label :distance_from_sun %>
        <br>
        <%= form.text_field :distance_from_sun %> (In AU(Astronomical Units))
        <br>
        <br>
    </div>

    <div class="fields">
        <%= form.label :moons %>
        <br>
        <%= form.text_field :moons %>
        <br>
        <br>
    </div>
    
    <%= form.label :image %>
    <%= form.file_field :image %>
    <br>
    <br>

    <div class="actions">
        <%= form.submit 'Submit' %>
    </div>
<% end %>
<br>
<br>

app/views/planets/edit.html.erb
<h1 align="center"><b>Editing Planet</b></h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Back', planets_path %>

app/views/planets/index.html.erb
<h1 align="center"><b>Planets</b></h1>

<h3>Search by Planet Name:</h3>
<%= form_tag(planets_path, :method => "get") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Planets" %>
  <%= submit_tag "Search" %>
<% end %>

<h4 align="center"><%= link_to "Add a Planet", new_planet_path %></h4>
<% @planets.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |planet| %>
      <div class="col-md-4">
        <%= image_tag planet.image_url(:thumb) if planet.image.present? %>
        <h4><%= link_to planet.name, planet %></h4>
        <p><b>Type of Planet: </b><%= planet.type_of_planet %></p>
        <p><b>Description: </b><%= planet.description %></p>
        <p><b>Length of Year: </b><%= planet.length_of_year %></p>
        <p><b>Distance from the Sun: </b><%= planet.distance_from_sun %></p>
        <p><b>Moons: </b><%= planet.moons %></p>
        <%= link_to 'Show', planet_path(planet) %><br>
        <%= link_to 'Edit', edit_planet_path(planet) %><br>
        <%= link_to 'Delete', planet_path(planet), method: :delete, data: { confirm: 'Are you sure?' } %>
        <br><br>
      </div>
    <% end %>
  </div>
<% end %>

app/views/planets/new.html.erb
<h1 align="center"><b>New Planet</b></h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Back', planets_path %>

app/views/planets/show.html.erb
<h1 align="center"><b><%= @planet.name %></b></h1><br>
<div class="row">
  <div class="col-md-9">
    <%= image_tag(@planet.image_url, width: '100%') if @planet.image.present? %>
  </div>

  <div class="col-md-3">
    <p><b>Name: </b><%= @planet.name %></p>
    <p><b>Type of Planet: </b><%= @planet.type_of_planet %></p>
    <p><b>Description: </b><%= @planet.description %></p>
    <p><b>Length of Year: </b><%= @planet.length_of_year %></p>
    <p><b>Distance from the Sun: </b><%= @planet.distance_from_sun %></p>
    <p><b>Moons: </b><%= @planet.moons %></p>
    <p>
      <%= link_to 'Add a new comment', new_planet_comment_path(@planet) %>
      <br>
      <%= link_to 'Edit', edit_planet_path(@planet) %> |
      <%= link_to 'Back', planets_path %>
    </p>
  </div>
</div>
<br>

<% if !@planet.comments.empty? %>
  <p><%= link_to 'See all comments', planet_comments_path(@planet)%></p>
  <h3>Most Recent Comments:</h3>
  <% @planet.comments.order(updated_at: :desc).limit(10).each do |comment| %>
    <strong><%= comment.user.username%></strong> says "<%= link_to comment.content, planet_comment_path(@planet,comment)%>" <br>at <%= comment.updated_at.strftime("%I:%M %p on %m/%d/%Y") %>
    <br>
    <%= link_to 'Edit', edit_planet_comment_path(@planet,comment) %> |
    <%= link_to 'Back', planets_path %> |
    <%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <br><br>
  <% end %>
<% end %>
<br>
<br>