config/routes.rb
Rails.application.routes.draw do
  #root
  root "sessions#home"

  #signup
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login
  get '/login' => 'sessions#login'
  post '/login' => 'sessions#create'

  #logged_in
  get '/user' => 'users#show'

  #logout
  delete '/logout' => 'sessions#destroy'

  #search planets
  get '/search' => 'planets#search'
  
  resources :moons
  resources :comments
  resources :users do
    resources :planets, only: [:new, :create, :index, :show]
    resources :moons, only: [:new, :create, :index, :show]
  end

  resources :planets do
    resources :comments
  end


  get '/auth/google_oauth2/callback', to: 'sessions#google_login'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

        <ul>
            <% object.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/x-icon" href="<%= asset_path('solar_system.ico')%>" />
    <title>Amateur Astronomer App</title>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand"href="/user">Amateur Astronomer App</a>
          </div>
          <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li class="active"><%= link_to "Planets", planets_path %></li>
                <li class="active"><%= link_to "Moons", moons_path %></li>
              </ul>
              <p class="navbar-text">
              <% if current_user %>
                <%= link_to "Logout", logout_path, method: :delete %>
              <% else %>
                <%= link_to "Log In", login_path %> | 
                <%= link_to "Sign Up", signup_path %> |
                <%= link_to "Sign Up with Google", '/auth/google_oauth2' %>
              <% end %>
              </p>
          </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    <div class="footer">
      <div class="footer_contents">
          Amateur Astronomers App 2020
      </div>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    </footer>
  </body>
</html>